/// Flutter icons Home
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Home
///      fonts:
///       - asset: fonts/Home.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Home {
  Home._();

  static const _kFontFam = 'Home';
  static const _kFontPkg = null;

  static const IconData logo = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
